bigquery: 
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: glean-web
      dataset: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
