repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies:
          - prefect
          - duckdb
          - types-requests
          - pandas-stubs
          - boto3-stubs
        args:
          - "--disallow-untyped-calls"
          - "--disallow-untyped-defs"
          - "--disallow-incomplete-defs"
          - "--strict-optional"
          - "--warn-return-any"
          - "--warn-no-return"
          - "--warn-redundant-casts"
          - "--no-warn-unused-ignores"
          - "--allow-untyped-decorators"
