# Runs the dbt pipeline against a new dataset, then creates a preview build in Hashboard.
name: hashboard-preview

on: [pull_request]

jobs:
  create-hashboard-build:
    name: "Create Hashboard build"
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: pip install --pre hashboard-cli
      - name: Create Hashboard build
        id: create-hb-build
        env:
          HASHBOARD_PROJECT_ID: ${{ secrets.PIZZABYTES_HB_PROJECT_ID }}
          HASHBOARD_ACCESS_KEY_ID: ${{ secrets.PIZZABYTES_HB_ACCESS_KEY_ID }}
          HASHBOARD_SECRET_ACCESS_KEY_TOKEN: ${{ secrets.PIZZABYTES_HB_SECRET_ACCESS_KEY_TOKEN }}
        run: |
          TERM=dumb hb build 2>&1 | tee out.txt
          EXIT_CODE=${PIPESTATUS[0]}

          RESULT=$(cat out.txt | sed 's/`//g')
          URL=$(grep -o 'https://[^ ]*' out.txt)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "log<<$EOF" >> $GITHUB_OUTPUT
          echo "$RESULT" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "exitCode=$EXIT_CODE" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        name: "Comment on the pull request"
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[Hashboard build](${{ steps.create-hb-build.outputs.url }})\n\`\`\`${{ steps.create-hb-build.outputs.log }}`
            })
      - id: set-appropriate-exit-code
        name: "Set exit code"
        run: echo ${{ steps.create-hb-build.outputs.exitCode }} | grep succeeded
